name: scully

dependencies:
    - beautifulsoup4
    - jupyter
    - ipython
    - matplotlib
    - pandas
    - pip
    - pip:
        - schedule
        - slackclient
        - stop-words
        - twython
    - pytest
    - python=3.5
