name: scully

dependencies:
    - beautifulsoup4
    - jupyter
    - ipython
    - matplotlib
    - pandas
    - pip
    - scikit-learn
    - pip:
        - schedule
        - slackclient
        - stop-words
        - twython
        - yahoo-finance
    - pytest
    - python=3.5
